# Generated by https://smithery.ai. See: https://smithery.ai/docs/build/project-config
FROM node:lts-alpine

# Install dependencies
WORKDIR /app
COPY package.json pnpm-lock.yaml ./
# Install PNPM
RUN npm install -g pnpm
# Install deps and build
COPY . .
RUN pnpm install && pnpm run build

# Default command
CMD ["node", "build/index.js"]
