# Generated by https://smithery.ai. See: https://smithery.ai/docs/build/project-config
FROM node:lts-alpine

# Create app directory
WORKDIR /app

# Install app dependencies
COPY package.json package-lock.json* pnpm-lock.yaml* ./
# Use npm install; ignore scripts to avoid prepublish or postinstall issues
RUN npm install --ignore-scripts

# Bundle app source
COPY . .

# Build the TypeScript source
RUN npm run build

# Expose default port (if HTTP; but stdio server doesn't need port)
# Set default command
CMD ["node", "build/index.js"]
